[project]
name = "swarmauri_transport_uds_unicast"
version = "0.1.0.dev2"
authors = [
    { name = "Jacob Stewart", email = "jacob@swarmauri.com" }
]
description = "Unix domain socket unicast transport for Swarmauri."
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/swarmauri/swarmauri-sdk"
requires-python = ">=3.10,<3.13"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "swarmauri-base",
    "swarmauri_core",
]
keywords = [
    'swarmauri',
    'sdk',
    'standards',
    'transport',
    'uds',
    'unicast',
]

[tool.uv.sources]
swarmauri-base = { workspace = true }
swarmauri_core = { workspace = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "python-dotenv",
    "requests>=2.32.3",
    "flake8>=7.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.9",
    "pytest-benchmark>=4.0.0",
]
