[tool.poetry]
name = "swarmauri-standard"
version = "0.6.0.dev175"
description = "This repository includes standard components within the Swarmauri framework."
authors = ["Jacob Stewart <jacob@swarmauri.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/swarmauri/swarmauri-sdk"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

# Swarmauri
swarmauri_core = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/core"}
swarmauri_base = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/base"}

# Dependencies
toml = "^0.10.2"
httpx = "^0.27.0"
numpy = "*"
pandas = "*"
pydantic = "^2.9.2"
typing_extensions = "*"

#####################
# Technical Debt
#
#####################
# Should only appear on a standalone package
scikit-learn = "^1.6.1"
matplotlib = "^3.10.0"
Pillow = ">=8.0,<11.0"
BeautifulSoup = "^3.2.2"
scipy = "^1.15.2"
yake = "^0.4.8"

# Are we dependent upon this forever?
aiofiles = { version = "24.1.0"}

# We should remove and only rely on httpx
requests = "^2.32.3"

# what requires joblib?
joblib = "^1.4.0"
###########################





[tool.poetry.group.dev.dependencies]
flake8 = "^7.0"
pytest = "^8.0"
pytest-asyncio = ">=0.23.8"
pytest-timeout = "^2.3.1"
pytest-xdist = "^3.6.1"
pytest-json-report = "^1.5.0"
python-dotenv = "^1.0.0"
jsonschema = "^4.18.5"
ipython = "^8.28.0"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]
asyncio_mode = "auto"

markers = [
    "test: standard test",
    "unit: Unit tests",
    "integration: Integration tests",
    "i9n: Integration tests",
    "r8n: Regression tests",
    "acceptance: Acceptance tests",
    "experimental: Experimental tests",
    "timeout: mark test to timeout after X seconds",
]

log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

asyncio_default_fixture_loop_scope = "function"
