[project]
name = "swarmauri-transport-tcpunicast"
version = "0.1.0"
description = "Basic TCP unicast transport for Swarmauri prototyping."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Jacob Stewart", email = "jacob@swarmauri.com" }]
license = { file = "LICENSE" }
dependencies = [
    "swarmauri-base",
    "swarmauri-core",
]
keywords = [
    "swarmauri",
    "tcp",
    "transport",
    "asyncio",
    "networking",
    "prototype",
    "sdk",
    "unicast",
    "agents",
    "microservices",
    "standards",
    "tcpunicast",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet",
    "Topic :: System :: Networking",
]

[project.urls]
Homepage = "https://github.com/swarmauri/swarmauri-sdk"
Repository = "https://github.com/swarmauri/swarmauri-sdk"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
