[project]
name = "jaml"
version = "0.2.0.dev6"
description = "Swarmauri's Canon Jaml Handler"
authors = [{ name = "Jacob Stewart", email = "jacob@swarmauri.com" }]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/swarmauri/swarmauri-sdk/pkgs/jaml"
requires-python = ">=3.10,<3.13"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "lark",
]
[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]
markers = [
    "test: standard test",
    "unit: Unit tests",
    "i9n: Integration tests",
    "r8n: Regression tests",
    "timeout: mark test to timeout after X seconds",
    "xpass: Expected passes",
    "xfail: Expected failures",
    "acceptance: Acceptance tests",
    "spec: Specification conformance tests",
    "perf: Performance tests that measure execution time and resource usage",
    "mep0001: MEP-0001 Specification Tests",
    "mep0002: MEP-0002 Specification Tests",
    "mep0003: MEP-0003 Specification Tests",
    "mep0004: MEP-0004 Specification Tests",
    "mep0005: MEP-0005 Specification Tests",
    "mep0006: MEP-0006 Specification Tests",
    "mep0007: MEP-0007 Specification Tests",
    "mep0008: MEP-0008 Specification Tests",
    "mep0009: MEP-0009 Specification Tests",
    "mep0010: MEP-0010 Specification Tests",
    "mep0011: MEP-0011 Specification Tests",
    "mep0011a: MEP-0011a Specification Tests",
    "mep0011b: MEP-0011b Specification Tests",
    "mep0012: MEP-0012 Specification Tests",
    "mep0013: MEP-0013 Specification Tests",
    "mep0014: MEP-0014 Specification Tests",
    "mep0028: MEP-0028 Specification Tests",
    "mep0028a: MEP-0028a Specification Tests",
    "mep0028b: MEP-0028b Specification Tests",
    "mep0028c: MEP-0028c Specification Tests",
    "mep0028d: MEP-0028d Specification Tests",
    "mep0028e: MEP-0028e Specification Tests",
    "mep0028f: MEP-0028f Specification Tests",
    "mep0028g: MEP-0028g Specification Tests",
]
timeout = 300
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_default_fixture_loop_scope = "function"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "python-dotenv",
    "requests>=2.32.3",
    "flake8>=7.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.9",
    "pytest-benchmark>=4.0.0",
]
