[tool.poetry]
name = "monorepo-manager"
version = "0.6.0.dev160"
description = "A CLI for managing a Python monorepo"
authors = [
  { name="Your Name", email="you@example.com" }
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
requests = "*"
tomlkit = "*"
packaging = "*"


[tool.project.scripts]
monorepo-manager = "monorepo_manager.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"