[project]
name = "zdx"
version = "0.2.0.dev16"
description = "Z Doc Builder Experience by Swarmauri"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12,<3.13"
authors = [{ name = "Jacob Stewart", email = "jacob@swarmauri.com" }]
keywords = [
    "mkdocs",
    "documentation",
    "swarmauri",
    "docs",
    "doc builder",
    "zdx",
    "doc",
    "builder",
    "experience",
]
dependencies = [
    "mkdocs",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-material>=9.6.4,<10.0.0",
    "mkdocstrings[python]>=0.28.1,<0.29.0",
    "mkdocs-autorefs",
    "griffe-typingdoc",
    "pyyaml>=6.0",
    "ruff>=0.5",
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[project.scripts]
zdx = "zdx.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "zdx" }]
include = [
    { path = "docs" },
    { path = "mkdocs.yml" },
    { path = "mkdocs.insiders.yaml" },
    { path = "api_manifest.yaml" },
    { path = "Dockerfile" },
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "python-dotenv",
    "requests>=2.32.3",
    "flake8>=7.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.9",
    "pytest-benchmark>=4.0.0",
]
