[tool.poetry]
name = "swarmauri_toolkit_jupytertoolkit"
version = "0.1.1.dev1"
description = "A unified toolkit for aggregating standalone jupyter notebook tools."
authors = ["Jacob Stewart <jacob@swarmauri.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/swarmauri/swarmauri-sdk/pkgs//swarmauri_toolkit_jupytertoolkit/"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
keywords = [
    "jupyter",
    "notebook",
    "toolkit",
    "swarmauri"
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

# Swarmauri
swarmauri_core = {git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/core"}
swarmauri_base = {git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/base"}
swarmauri_standard = {git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_standard"}

# Community
swarmuri_tool_jupyterclearoutput = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterclearoutput"}
swarmuri_tool_jupyterdisplay = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterdisplay"}
swarmuri_tool_jupyterdisplayhtml = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterdisplayhtml"}
swarmuri_tool_jupyterexecuteandconvert = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexecuteandconvert"}
swarmuri_tool_jupyterexecutecell = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexecutecell"}
swarmuri_tool_jupyterexecutenotebook = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexecutenotebook"}
swarmuri_tool_jupyterexecutenotebookwithparameters = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexecutenotebookwithparameters"}
swarmuri_tool_jupyterexporthtml = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexporthtml"}
swarmuri_tool_jupyterexportlatex = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexportlatex"}
swarmuri_tool_jupyterexportmarkdown = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexportmarkdown"}
swarmuri_tool_jupyterexportpython = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterexportpython"}
swarmuri_tool_jupyterfromdict = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterfromdict"}
swarmuri_tool_jupytergetiopubmessage = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupytergetiopubmessage"}
swarmuri_tool_jupytergetshellmessage = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupytergetshellmessage"}
swarmuri_tool_jupyterreadnotebook = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterreadnotebook"}
swarmuri_tool_jupyterruncell = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterruncell"}
swarmuri_tool_jupytershutdownkernel = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupytershutdownkernel"}
swarmuri_tool_jupyterstartkernel = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterstartkernel"}
swarmuri_tool_jupytervalidatenotebook = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupytervalidatenotebook"}
swarmuri_tool_jupyterwritenotebook = { git = "https://github.com/swarmauri/community.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_tool_jupyterwritenotebook"}

# Dependencies
pydantic = "*"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0"
pytest = "^8.0"
pytest-asyncio = ">=0.24.0"
pytest-xdist = "^3.6.1"
pytest-json-report = "^1.5.0"
python-dotenv = "*"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "unit: Unit tests",
    "i9n: Integration tests",
    "xfail: Expected failures",
    "xpass: Expected passes"
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_default_fixture_loop_scope = "function"

[tool.poetry.plugins."swarmauri.toolkits"]
jupytertoolkit = "swarmauri_toolkit_jupytertoolkit:JupyterToolkit"