name: Deploy Docs Infra
on:
  workflow_dispatch:

concurrency:
  group: docs-deploy
  cancel-in-progress: true

jobs:
  deploy-infra:
    if: ${{ !cancelled() }}
    runs-on: [docs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restart docs infra stack
        run: |
          sudo docker compose -f infra/docs/docker-compose.yaml down || true
          sudo docker compose -f infra/docs/docker-compose.yaml up -d --pull always
